# Dependencies
markdown: 		  rdiscount
highlighter: 	  rouge

# Permalinks
permalink:        pretty

# Setup
title:            Benjamin Bergner
tagline:          The Jekyll Butler
url:              "http://benjaminbergner.github.io/"
paginate:         1
baseurl:          _config.yml
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
