# Dependencies
markdown: 		  redcarpet
pygments:		  true

# Permalinks
permalink:        pretty

# Setup
title:            Benjamin Bergner
tagline:          Blog
url:              http://benjaminbergner.github.io/
paginate:         1
baseurl:          http://benjaminbergner.github.io/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
