# Dependencies
markdown: 		  redcarpet
pygments:		  true

# Permalinks
permalink:        pretty

# Setup
title:            Benjamin Bergner
tagline:          Blog
url:              http://benjaminbergner.net
paginate:         1
baseurl:          /
author:
  name:           Benjamin Bergner
  url:            https://benjaminbergner.net
  email:          bergner.benjamin@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

pages_list:       
  Über mich: '/about'
  Alle Beiträge: '/archive'
  Feed: '/atom.xml'
