# Dependencies
markdown: 		  rdiscount
highlighter: 	  rouge

# Permalinks
permalink:        pretty

# Setup
title:            Benjamin Bergne
tagline:          The Jekyll Butler
url:              "http://benjaminbergner.github.io/poole/"
paginate:         1
baseurl:          "http://benjaminbergner.github.io/poole/"
safe: true
lsi: false

author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           "https://github.com/benjaminbergner/benjaminbergner.github.io/poole/"

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
